### ISSUE TITLE
running scripts in web-worker allows network requests to use host's origin and cookies

### ISSUE THREAD

**Issue by cheapsteak** [postmanlabs/uvm#411]
I worry if this PR to change sandboxing from iframe to webworker may have made this lib less secure https://github.com/postmanlabs/uvm/pull/407

It looks like the worker version can access the host's api without needing any extra CORS headers
https://codesandbox.io/s/uvm-test-l6t2b?file=/pages/index.js (tested using 1.8.0-beta.1), the requests also seem to carry the same cookies as ones made from the host

on [1.7.9](https://codesandbox.io/s/uvm-test-179-dql85?file=/pages/index.js), that same fetch would fail with 

>Access to fetch at 'https://l6t2b.sse.codesandbox.io/api/test' from origin 'null' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

**Comment by codenirvana** [comment]
Hey, @cheapsteak 👋 thanks for testing our prerelease package and raising this security concern.

I would like to first answer your question posted here https://github.com/postmanlabs/uvm/pull/407#issuecomment-696184799,
> Curious what motivated this change from using a sandboxed iframe to a webworker?

This change is made because of two primary reasons:
1. iFrame inharits the parent CSP when created using `data:` or `srcdoc`. This means, the parent window has to loosen the CSP and allow inline script. Because a nonce can't be added in this particular case.
2. Same event loop (window event loop) is used for the iFrame and parent. Which means, a synchronous script execution in iFrame will block the UI intercations in parent window.

> I worry if this PR to change sandboxing from iframe to webworker may have made this lib less secure #407

This library doesn't provide a security sandbox. This module just exposes an event emitter to send data across contexts.

So, you are right... this change does exposed a lot of WebAPI which was previously blocked because of the `sandbox` attribute and we are aware of these security implications and addressing this issue in https://github.com/postmanlabs/postman-sandbox/pull/605.
Postman Sandbox uses this module internally and to make sure these WebAPIs are not available, we are mutating the worker scope by deleting all the forbidden [globals](https://github.com/postmanlabs/uniscope/blob/develop/lib/allowed-globals.js).

Finally, I would like to know more about your usecase. Are you using this library in your project?
Will you be affected because of this change? If so, we can actually expose an option to use the `iFrame` sandbox if needed.

**Comment by cheapsteak** [comment]
Thank you so much for the incredibly thorough explanation! That all makes a lot of sense  

Please don't add the maintenance burden of a different target to support just on my account; I do wish such a package existed in the ecosystem for site who haven't set about CSPs for script-src yet, but I think it should be sufficient for me to reference how globals are deleted from the linked PR and see if I can do a similar thing :)
